site_name: PPS 21-22
site_url: https://fpieseljust.github.io/pps21-22/
docs_dir: 'md'
site_dir: 'docs'
nav:
    - Home: index.md
    - Unitats:
      - Unitat 1 - Introducci贸 a la programaci贸 segura:
        - TDD: Unitats/Unitat 1/TDD.md
        - CD/CI: Unitats/Unitat 1/CD-CI.md
      - Unitat 3 - Detecci贸 i correcci贸 de vulnerabilitats en aplicacions web:
        - API Rest: Unitats/Unitat 3/APIRest.md
    - About: about.md
theme:
  name: material
